### ISSUE TITLE
Invalid Feed Input Name

### ISSUE THREAD

**Issue by fisakhan** [cassiebreviu/cpp-onnxruntime-resnet-console-app#1]
Thanks @cassiebreviu for this code and tutorial on YouTube.

I get the following error:

> Invalid Feed Input Name:�L�5�U

The error is generated by the following line:
`session.Run(runOptions, inputNames.data(), &inputTensor, 1, outputNames.data(), &outputTensor, 1);`

I display inputName and outputName, which are some random characters. What values of inputName and outputName should I expect? 

Can you please help me how to run this code successfully?

**Comment by cassiebreviu** [comment]
The error message indicated that the input feed input name is invalid. I dont know the source cause without seeing your model. But its likely an issue with how the input name was set when you serialized the model, please check the onnx model input names.

**Comment by fisakhan** [comment]
@cassiebreviu thanks but I'm using only this repository and the model provided in assets sub-directory (resnet50v2.onnx). It is the same code and model that you provided. Why is it not working?

**Comment by fisakhan** [comment]
I found the problem and solved it. 
Comment the following two lines:
ort_alloc.Free(inputName);
ort_alloc.Free(outputName);
